[project]
name = "deeptodos"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.123.5",
    "fastapi-users[sqlalchemy]>=15.0.1",
    "uvicorn[standard]>=0.38.0",
]
